/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iPoolSol from "./IPool.sol";
export type { iPoolSol };
export type { IAToken } from "./IAToken";
