/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dcaReinvestModualTemplateSol from "./DCAReinvestModual.template.sol";
export type { dcaReinvestModualTemplateSol };
import type * as lidoStakingSol from "./LidoStaking.sol";
export type { lidoStakingSol };
export type { AaveV3Reinvest } from "./AaveV3Reinvest";
export type { CompoundV3Reinvest } from "./CompoundV3Reinvest";
export type { ForwardReinvest } from "./ForwardReinvest";
