/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface LidoReinvestInterface extends Interface {
  getFunction(
    nameOrSignature: "LIDO_CONTRACT" | "MODULE_ID" | "MODULE_NAME"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "LIDO_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MODULE_ID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MODULE_NAME",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "LIDO_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MODULE_ID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MODULE_NAME",
    data: BytesLike
  ): Result;
}

export interface LidoReinvest extends BaseContract {
  connect(runner?: ContractRunner | null): LidoReinvest;
  waitForDeployment(): Promise<this>;

  interface: LidoReinvestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIDO_CONTRACT: TypedContractMethod<[], [string], "view">;

  MODULE_ID: TypedContractMethod<[], [bigint], "view">;

  MODULE_NAME: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIDO_CONTRACT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MODULE_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MODULE_NAME"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
