/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  AaveV3Reinvest,
  AaveV3ReinvestInterface,
} from "../../../contracts/modules/AaveV3Reinvest";

const _abi = [
  {
    inputs: [],
    name: "MODULE_ID",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MODULE_NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61015361003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100405760003560e01c80639b865b4314610045578063ed2f21f514610097575b600080fd5b6100816040518060400160405280601081526020017f41617665205633205265696e766573740000000000000000000000000000000081525081565b60405161008e91906100b1565b60405180910390f35b61009f601281565b60405160ff909116815260200161008e565b600060208083528351808285015260005b818110156100de578581018301518582016040015282016100c2565b5060006040828601015260407fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0601f830116850101925050509291505056fea2646970667358221220f9404d2edcbba6f70feb8e4e8b303941b5d80abf2aa6968ef6fbda5241772c5e64736f6c63430008140033";

type AaveV3ReinvestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AaveV3ReinvestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AaveV3Reinvest__factory extends ContractFactory {
  constructor(...args: AaveV3ReinvestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AaveV3Reinvest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AaveV3Reinvest__factory {
    return super.connect(runner) as AaveV3Reinvest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AaveV3ReinvestInterface {
    return new Interface(_abi) as AaveV3ReinvestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AaveV3Reinvest {
    return new Contract(address, _abi, runner) as unknown as AaveV3Reinvest;
  }
}
