/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  AaveV3Reinvest,
  AaveV3ReinvestInterface,
} from "../../../contracts/modules/AaveV3Reinvest";

const _abi = [
  {
    inputs: [],
    name: "MODULE_ID",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MODULE_NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61011e61003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603d5760003560e01c80639b865b43146042578063ed2f21f5146084575b600080fd5b60706040518060400160405280601081526020016f10585d9948158cc814995a5b9d995cdd60821b81525081565b604051607b9190609c565b60405180910390f35b608b601281565b60405160ff9091168152602001607b565b600060208083528351808285015260005b8181101560c75785810183015185820160400152820160ad565b506000604082860101526040601f19601f830116850101925050509291505056fea2646970667358221220c81dbec737acf7afb7e841748204607c6910501325f225493e41c0c3334e3d0e64736f6c63430008140033";

type AaveV3ReinvestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AaveV3ReinvestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AaveV3Reinvest__factory extends ContractFactory {
  constructor(...args: AaveV3ReinvestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AaveV3Reinvest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AaveV3Reinvest__factory {
    return super.connect(runner) as AaveV3Reinvest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AaveV3ReinvestInterface {
    return new Interface(_abi) as AaveV3ReinvestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AaveV3Reinvest {
    return new Contract(address, _abi, runner) as unknown as AaveV3Reinvest;
  }
}
