/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  CompoundV3Reinvest,
  CompoundV3ReinvestInterface,
} from "../../../contracts/modules/CompoundV3Reinvest";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
    ],
    name: "ApprovalFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "MODULE_ID",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MODULE_NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61012261003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603d5760003560e01c80639b865b43146042578063ed2f21f5146088575b600080fd5b60746040518060400160405280601481526020017310dbdb5c1bdd5b9908158cc814995a5b9d995cdd60621b81525081565b604051607f919060a0565b60405180910390f35b608f601181565b60405160ff9091168152602001607f565b600060208083528351808285015260005b8181101560cb5785810183015185820160400152820160b1565b506000604082860101526040601f19601f830116850101925050509291505056fea26469706673582212204177de390b7aeb56887ba491e6f9f0cc38cdfbe2ce966f41a3196977638e372564736f6c63430008140033";

type CompoundV3ReinvestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CompoundV3ReinvestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CompoundV3Reinvest__factory extends ContractFactory {
  constructor(...args: CompoundV3ReinvestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CompoundV3Reinvest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CompoundV3Reinvest__factory {
    return super.connect(runner) as CompoundV3Reinvest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CompoundV3ReinvestInterface {
    return new Interface(_abi) as CompoundV3ReinvestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CompoundV3Reinvest {
    return new Contract(address, _abi, runner) as unknown as CompoundV3Reinvest;
  }
}
