/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDCADataStructures {
  export type TokenDataStruct = {
    tokenAddress: AddressLike;
    decimals: BigNumberish;
    ticker: string;
  };

  export type TokenDataStructOutput = [
    tokenAddress: string,
    decimals: bigint,
    ticker: string
  ] & { tokenAddress: string; decimals: bigint; ticker: string };

  export type ReinvestStruct = {
    reinvestData: BytesLike;
    active: boolean;
    investCode: BigNumberish;
    dcaAccountAddress: AddressLike;
  };

  export type ReinvestStructOutput = [
    reinvestData: string,
    active: boolean,
    investCode: bigint,
    dcaAccountAddress: string
  ] & {
    reinvestData: string;
    active: boolean;
    investCode: bigint;
    dcaAccountAddress: string;
  };

  export type StrategyStruct = {
    accountAddress: AddressLike;
    baseToken: IDCADataStructures.TokenDataStruct;
    targetToken: IDCADataStructures.TokenDataStruct;
    interval: BigNumberish;
    amount: BigNumberish;
    strategyId: BigNumberish;
    active: boolean;
    reinvest: IDCADataStructures.ReinvestStruct;
  };

  export type StrategyStructOutput = [
    accountAddress: string,
    baseToken: IDCADataStructures.TokenDataStructOutput,
    targetToken: IDCADataStructures.TokenDataStructOutput,
    interval: bigint,
    amount: bigint,
    strategyId: bigint,
    active: boolean,
    reinvest: IDCADataStructures.ReinvestStructOutput
  ] & {
    accountAddress: string;
    baseToken: IDCADataStructures.TokenDataStructOutput;
    targetToken: IDCADataStructures.TokenDataStructOutput;
    interval: bigint;
    amount: bigint;
    strategyId: bigint;
    active: boolean;
    reinvest: IDCADataStructures.ReinvestStructOutput;
  };
}

export interface IDCAExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DistributeFees"
      | "Execute"
      | "ForceUnsubscribe"
      | "Subscribe"
      | "Unsubscribe"
      | "getTimeTillWindow"
      | "setIntervalActive"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutedStrategy"
      | "FeeDataChanged"
      | "FeesDistributed"
      | "StrategySubscription"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DistributeFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "Execute",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ForceUnsubscribe",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "Subscribe",
    values: [IDCADataStructures.StrategyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "Unsubscribe",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeTillWindow",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setIntervalActive",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "DistributeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ForceUnsubscribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "Unsubscribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeTillWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIntervalActive",
    data: BytesLike
  ): Result;
}

export namespace ExecutedStrategyEvent {
  export type InputTuple = [account_: AddressLike, strategyId_: BigNumberish];
  export type OutputTuple = [account_: string, strategyId_: bigint];
  export interface OutputObject {
    account_: string;
    strategyId_: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeDataChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesDistributedEvent {
  export type InputTuple = [token_: AddressLike, amount_: BigNumberish];
  export type OutputTuple = [token_: string, amount_: bigint];
  export interface OutputObject {
    token_: string;
    amount_: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategySubscriptionEvent {
  export type InputTuple = [
    DCAAccountAddress_: AddressLike,
    strategyId_: BigNumberish,
    strategyInterval_: BigNumberish,
    active_: boolean
  ];
  export type OutputTuple = [
    DCAAccountAddress_: string,
    strategyId_: bigint,
    strategyInterval_: bigint,
    active_: boolean
  ];
  export interface OutputObject {
    DCAAccountAddress_: string;
    strategyId_: bigint;
    strategyInterval_: bigint;
    active_: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDCAExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): IDCAExecutor;
  waitForDeployment(): Promise<this>;

  interface: IDCAExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DistributeFees: TypedContractMethod<
    [tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  Execute: TypedContractMethod<
    [DCAAccount_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  ForceUnsubscribe: TypedContractMethod<
    [DCAAccount_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  Subscribe: TypedContractMethod<
    [strategy_: IDCADataStructures.StrategyStruct],
    [void],
    "nonpayable"
  >;

  Unsubscribe: TypedContractMethod<
    [DCAAccountAddress_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTimeTillWindow: TypedContractMethod<
    [account_: AddressLike, strategyId_: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        lastEx: bigint;
        secondsLeft: bigint;
        checkReturn: boolean;
      }
    ],
    "view"
  >;

  setIntervalActive: TypedContractMethod<
    [interval_: BigNumberish, status_: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DistributeFees"
  ): TypedContractMethod<[tokenAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "Execute"
  ): TypedContractMethod<
    [DCAAccount_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ForceUnsubscribe"
  ): TypedContractMethod<
    [DCAAccount_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "Subscribe"
  ): TypedContractMethod<
    [strategy_: IDCADataStructures.StrategyStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "Unsubscribe"
  ): TypedContractMethod<
    [DCAAccountAddress_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTimeTillWindow"
  ): TypedContractMethod<
    [account_: AddressLike, strategyId_: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        lastEx: bigint;
        secondsLeft: bigint;
        checkReturn: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setIntervalActive"
  ): TypedContractMethod<
    [interval_: BigNumberish, status_: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ExecutedStrategy"
  ): TypedContractEvent<
    ExecutedStrategyEvent.InputTuple,
    ExecutedStrategyEvent.OutputTuple,
    ExecutedStrategyEvent.OutputObject
  >;
  getEvent(
    key: "FeeDataChanged"
  ): TypedContractEvent<
    FeeDataChangedEvent.InputTuple,
    FeeDataChangedEvent.OutputTuple,
    FeeDataChangedEvent.OutputObject
  >;
  getEvent(
    key: "FeesDistributed"
  ): TypedContractEvent<
    FeesDistributedEvent.InputTuple,
    FeesDistributedEvent.OutputTuple,
    FeesDistributedEvent.OutputObject
  >;
  getEvent(
    key: "StrategySubscription"
  ): TypedContractEvent<
    StrategySubscriptionEvent.InputTuple,
    StrategySubscriptionEvent.OutputTuple,
    StrategySubscriptionEvent.OutputObject
  >;

  filters: {
    "ExecutedStrategy(address,uint256)": TypedContractEvent<
      ExecutedStrategyEvent.InputTuple,
      ExecutedStrategyEvent.OutputTuple,
      ExecutedStrategyEvent.OutputObject
    >;
    ExecutedStrategy: TypedContractEvent<
      ExecutedStrategyEvent.InputTuple,
      ExecutedStrategyEvent.OutputTuple,
      ExecutedStrategyEvent.OutputObject
    >;

    "FeeDataChanged()": TypedContractEvent<
      FeeDataChangedEvent.InputTuple,
      FeeDataChangedEvent.OutputTuple,
      FeeDataChangedEvent.OutputObject
    >;
    FeeDataChanged: TypedContractEvent<
      FeeDataChangedEvent.InputTuple,
      FeeDataChangedEvent.OutputTuple,
      FeeDataChangedEvent.OutputObject
    >;

    "FeesDistributed(address,uint256)": TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;
    FeesDistributed: TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;

    "StrategySubscription(address,uint256,uint8,bool)": TypedContractEvent<
      StrategySubscriptionEvent.InputTuple,
      StrategySubscriptionEvent.OutputTuple,
      StrategySubscriptionEvent.OutputObject
    >;
    StrategySubscription: TypedContractEvent<
      StrategySubscriptionEvent.InputTuple,
      StrategySubscriptionEvent.OutputTuple,
      StrategySubscriptionEvent.OutputObject
    >;
  };
}
