/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSwapRouterv3Sol from "./ISwapRouterv3.sol";
export type { iSwapRouterv3Sol };
export type { IUniversalRouter } from "./IUniversalRouter";
