/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as onlyActiveSol from "./onlyActive.sol";
export type { onlyActiveSol };
import type * as onlyAdminSol from "./onlyAdmin.sol";
export type { onlyAdminSol };
import type * as onlyExecutorSol from "./onlyExecutor.sol";
export type { onlyExecutorSol };
