/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DCAFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CreateAccount"
      | "SWAP_ROUTER"
      | "accountsCreated"
      | "getAccountsOfUser"
      | "getActiveExecutorAddress"
      | "getFactoryActiveState"
      | "getTotalDeployedAccounts"
      | "isActive"
      | "owner"
      | "pauseFactory"
      | "reInvestLogicContract"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpauseFactory"
      | "updateExecutorAddress"
      | "updateReinvestLibraryAddress"
      | "userDCAAccounts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountCreated"
      | "ContractActiveStateChange"
      | "ExecutorChanged"
      | "OwnershipTransferred"
      | "ReinvestLibraryChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CreateAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SWAP_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountsCreated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountsOfUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveExecutorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFactoryActiveState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDeployedAccounts",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reInvestLogicContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateExecutorAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReinvestLibraryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDCAAccounts",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CreateAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SWAP_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountsCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountsOfUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveExecutorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFactoryActiveState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDeployedAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reInvestLogicContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateExecutorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReinvestLibraryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDCAAccounts",
    data: BytesLike
  ): Result;
}

export namespace AccountCreatedEvent {
  export type InputTuple = [owner: AddressLike, dcaAccount: AddressLike];
  export type OutputTuple = [owner: string, dcaAccount: string];
  export interface OutputObject {
    owner: string;
    dcaAccount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractActiveStateChangeEvent {
  export type InputTuple = [active_: boolean];
  export type OutputTuple = [active_: boolean];
  export interface OutputObject {
    active_: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorChangedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReinvestLibraryChangedEvent {
  export type InputTuple = [newLibraryAddress: AddressLike];
  export type OutputTuple = [newLibraryAddress: string];
  export interface OutputObject {
    newLibraryAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DCAFactory extends BaseContract {
  connect(runner?: ContractRunner | null): DCAFactory;
  waitForDeployment(): Promise<this>;

  interface: DCAFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CreateAccount: TypedContractMethod<[], [void], "nonpayable">;

  SWAP_ROUTER: TypedContractMethod<[], [string], "view">;

  accountsCreated: TypedContractMethod<[], [bigint], "view">;

  getAccountsOfUser: TypedContractMethod<
    [_user: AddressLike],
    [string[]],
    "view"
  >;

  getActiveExecutorAddress: TypedContractMethod<[], [string], "view">;

  getFactoryActiveState: TypedContractMethod<[], [boolean], "view">;

  getTotalDeployedAccounts: TypedContractMethod<[], [bigint], "view">;

  isActive: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseFactory: TypedContractMethod<[], [void], "nonpayable">;

  reInvestLogicContract: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpauseFactory: TypedContractMethod<[], [void], "nonpayable">;

  updateExecutorAddress: TypedContractMethod<
    [_newExecutorAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updateReinvestLibraryAddress: TypedContractMethod<
    [newAddress_: AddressLike],
    [void],
    "nonpayable"
  >;

  userDCAAccounts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CreateAccount"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "SWAP_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accountsCreated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAccountsOfUser"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getActiveExecutorAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getFactoryActiveState"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getTotalDeployedAccounts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseFactory"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reInvestLogicContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseFactory"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateExecutorAddress"
  ): TypedContractMethod<
    [_newExecutorAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReinvestLibraryAddress"
  ): TypedContractMethod<[newAddress_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userDCAAccounts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "AccountCreated"
  ): TypedContractEvent<
    AccountCreatedEvent.InputTuple,
    AccountCreatedEvent.OutputTuple,
    AccountCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractActiveStateChange"
  ): TypedContractEvent<
    ContractActiveStateChangeEvent.InputTuple,
    ContractActiveStateChangeEvent.OutputTuple,
    ContractActiveStateChangeEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorChanged"
  ): TypedContractEvent<
    ExecutorChangedEvent.InputTuple,
    ExecutorChangedEvent.OutputTuple,
    ExecutorChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReinvestLibraryChanged"
  ): TypedContractEvent<
    ReinvestLibraryChangedEvent.InputTuple,
    ReinvestLibraryChangedEvent.OutputTuple,
    ReinvestLibraryChangedEvent.OutputObject
  >;

  filters: {
    "AccountCreated(address,address)": TypedContractEvent<
      AccountCreatedEvent.InputTuple,
      AccountCreatedEvent.OutputTuple,
      AccountCreatedEvent.OutputObject
    >;
    AccountCreated: TypedContractEvent<
      AccountCreatedEvent.InputTuple,
      AccountCreatedEvent.OutputTuple,
      AccountCreatedEvent.OutputObject
    >;

    "ContractActiveStateChange(bool)": TypedContractEvent<
      ContractActiveStateChangeEvent.InputTuple,
      ContractActiveStateChangeEvent.OutputTuple,
      ContractActiveStateChangeEvent.OutputObject
    >;
    ContractActiveStateChange: TypedContractEvent<
      ContractActiveStateChangeEvent.InputTuple,
      ContractActiveStateChangeEvent.OutputTuple,
      ContractActiveStateChangeEvent.OutputObject
    >;

    "ExecutorChanged(address)": TypedContractEvent<
      ExecutorChangedEvent.InputTuple,
      ExecutorChangedEvent.OutputTuple,
      ExecutorChangedEvent.OutputObject
    >;
    ExecutorChanged: TypedContractEvent<
      ExecutorChangedEvent.InputTuple,
      ExecutorChangedEvent.OutputTuple,
      ExecutorChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReinvestLibraryChanged(address)": TypedContractEvent<
      ReinvestLibraryChangedEvent.InputTuple,
      ReinvestLibraryChangedEvent.OutputTuple,
      ReinvestLibraryChangedEvent.OutputObject
    >;
    ReinvestLibraryChanged: TypedContractEvent<
      ReinvestLibraryChangedEvent.InputTuple,
      ReinvestLibraryChangedEvent.OutputTuple,
      ReinvestLibraryChangedEvent.OutputObject
    >;
  };
}
