/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ReinvestTemplate,
  ReinvestTemplateInterface,
} from "../../../../contracts/modules/LidoStaking.sol/ReinvestTemplate";

const _abi = [
  {
    inputs: [],
    name: "LIDO_CONTRACT",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MODULE_ID",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MODULE_NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61019e61003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061004b5760003560e01c80639b865b4314610050578063ade3eb11146100a2578063ed2f21f5146100e2575b600080fd5b61008c6040518060400160405280600a81526020017f4c69646f2073744554480000000000000000000000000000000000000000000081525081565b60405161009991906100fc565b60405180910390f35b6100bd733e3fe7dbc6b4c189e7128855dd526361c49b40af81565b60405173ffffffffffffffffffffffffffffffffffffffff9091168152602001610099565b6100ea601581565b60405160ff9091168152602001610099565b600060208083528351808285015260005b818110156101295785810183015185820160400152820161010d565b5060006040828601015260407fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0601f830116850101925050509291505056fea2646970667358221220cc10808047f99a490b8b5575c81087ebb0b674d26956ec23c5a09849eaaf0a1164736f6c63430008140033";

type ReinvestTemplateConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReinvestTemplateConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReinvestTemplate__factory extends ContractFactory {
  constructor(...args: ReinvestTemplateConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReinvestTemplate & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReinvestTemplate__factory {
    return super.connect(runner) as ReinvestTemplate__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReinvestTemplateInterface {
    return new Interface(_abi) as ReinvestTemplateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReinvestTemplate {
    return new Contract(address, _abi, runner) as unknown as ReinvestTemplate;
  }
}
