/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accountLogicSol from "./AccountLogic.sol";
export type { accountLogicSol };
import type * as reinvestLogicSol from "./ReinvestLogic.sol";
export type { reinvestLogicSol };
